image: node:11.11.0

before_script:
  - npm

cache:
  paths:
    - node_modules/

stages:
  - test
  - pages

unit:
  stage: test
  script:
    - npm test

build:
  stage: test
  script:
    - npm run build
  except:
    - master

pages:
  stage: pages
  script:
    - npm run build
  artifacts:
    paths:
      - public
  only:
    - master